name: Build Only
on:
  pull_request:
    branches: 
      - main
jobs:
  build:
    name: Build and Validate
    runs-on: ubuntu-20.04
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: w3c/spec-prod@v2
